title: "Rania BENBETKA"
logo: "/assets/img/headshot_circle.png"
description: "Welcome to my portfolio! Discover my projects and professional journey."
show_downloads: false
social_links:
  - name: LinkedIn
    url: "https://linkedin.com/in/rania-benbetka"
  - name: GitHub
    url: "https://github.com/your-username"
  - name: Email
    url: "mailto:your-email@example.com"
theme: jekyll-theme-cayman
